onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /MazeRunner_tb/FAST_SIM
add wave -noupdate /MazeRunner_tb/clk
add wave -noupdate /MazeRunner_tb/RST_n
add wave -noupdate /MazeRunner_tb/send_cmd
add wave -noupdate /MazeRunner_tb/cmd
add wave -noupdate /MazeRunner_tb/batt
add wave -noupdate /MazeRunner_tb/cmd_sent
add wave -noupdate /MazeRunner_tb/resp_rdy
add wave -noupdate /MazeRunner_tb/resp
add wave -noupdate /MazeRunner_tb/hall_n
add wave -noupdate /MazeRunner_tb/TX_RX
add wave -noupdate /MazeRunner_tb/RX_TX
add wave -noupdate /MazeRunner_tb/INRT_SS_n
add wave -noupdate /MazeRunner_tb/INRT_SCLK
add wave -noupdate /MazeRunner_tb/INRT_MOSI
add wave -noupdate /MazeRunner_tb/INRT_MISO
add wave -noupdate /MazeRunner_tb/INRT_INT
add wave -noupdate /MazeRunner_tb/lftPWM1
add wave -noupdate /MazeRunner_tb/lftPWM2
add wave -noupdate /MazeRunner_tb/rghtPWM1
add wave -noupdate /MazeRunner_tb/rghtPWM2
add wave -noupdate /MazeRunner_tb/A2D_SS_n
add wave -noupdate /MazeRunner_tb/A2D_SCLK
add wave -noupdate /MazeRunner_tb/A2D_MOSI
add wave -noupdate /MazeRunner_tb/A2D_MISO
add wave -noupdate /MazeRunner_tb/IR_lft_en
add wave -noupdate /MazeRunner_tb/IR_cntr_en
add wave -noupdate /MazeRunner_tb/IR_rght_en
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/state
add wave -noupdate /MazeRunner_tb/iDUT/iCMD/cmd_md
add wave -noupdate /MazeRunner_tb/iDUT/iCMD/state
add wave -noupdate /MazeRunner_tb/iDUT/iCMD/cmd
add wave -noupdate -divider maze_solve
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/PARAM_STARTUP_HDG
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/clk
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/rst_n
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/cmd_md
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/cmd0
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/lft_opn
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/rght_opn
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/mv_cmplt
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/sol_cmplt
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/strt_hdng
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/dsrd_hdng
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/strt_mv
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/stp_lft
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/stp_rght
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/turn_left
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/turn_right
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/turn_around
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/state
add wave -noupdate /MazeRunner_tb/iDUT/iSLV/nxt_state
add wave -noupdate -divider Navigate
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/FAST_SIM
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/MAX_FRWRD
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/MIN_FRWRD
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/clk
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/rst_n
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/strt_hdng
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/strt_mv
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/stp_lft
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/stp_rght
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/hdng_rdy
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/mv_cmplt
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/moving
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/en_fusion
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/at_hdng
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/lft_opn
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/rght_opn
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/frwrd_opn
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/frwrd_spd
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/lft_opn_ffd
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/rght_opn_ffd
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/lft_opn_rise
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/rght_opn_rise
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/frwrd_inc
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/state
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/nxt_state
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/init_frwrd
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/inc_frwrd
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/dec_frwrd
add wave -noupdate /MazeRunner_tb/iDUT/iNAV/dec_frwrd_fast
add wave -noupdate -divider {New Divider}
add wave -noupdate /MazeRunner_tb/iDUT/iMTR/lft_spd
add wave -noupdate /MazeRunner_tb/iDUT/iMTR/rght_spd
add wave -noupdate -radix hexadecimal /MazeRunner_tb/iPHYS/magnet_pos_xx
add wave -noupdate -radix hexadecimal /MazeRunner_tb/iPHYS/magnet_pos_yy
add wave -noupdate /MazeRunner_tb/iPHYS/xx
add wave -noupdate /MazeRunner_tb/iPHYS/yy
add wave -noupdate /MazeRunner_tb/iPHYS/lftIR
add wave -noupdate /MazeRunner_tb/iPHYS/cntrIR
add wave -noupdate /MazeRunner_tb/iPHYS/rghtIR
add wave -noupdate /MazeRunner_tb/iPHYS/omega_lft
add wave -noupdate /MazeRunner_tb/iPHYS/omega_rght
add wave -noupdate /MazeRunner_tb/iPHYS/alpha_lft
add wave -noupdate /MazeRunner_tb/iPHYS/alpha_rght
add wave -noupdate /MazeRunner_tb/iPHYS/mtrL1
add wave -noupdate /MazeRunner_tb/iPHYS/mtrL2
add wave -noupdate /MazeRunner_tb/iPHYS/mtrR1
add wave -noupdate /MazeRunner_tb/iPHYS/mtrR2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1923324 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 280
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {205520896 ns}
